# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "c1e5bb5ae782d88ff9466effa8b48498"
name = "layout-extention"
handle = "layout-extention"
application_url = "https://layout.fly.dev"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "malin-without-apps.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://layout.fly.dev/auth/callback",
  "https://layout.fly.dev/auth/shopify/callback",
  "https://layout.fly.dev/api/auth/callback"
]

[webhooks]
api_version = "2024-01"

[pos]
embedded = false
